Fmi3 Implementer's guide
modelica/newsletter pull request #238
Opened 2023-03-03 10:13 UTC by chrbertsch

2023-03-03 14:36 UTC, chrbertsch commented
@pmai : could you please review? Thanks!

2023-03-04 12:36 UTC, pmai requested changes
Looks good to me, adjusted according to fixes to the PR.

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +title: FMI 3.0 implementer’s guide jointly published by prostep ivip and Modelica Association Project FMI
```suggestion
title: FMI 3.0 Implementers' Guide jointly published by prostep ivip and Modelica Association Project FMI
```

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +#### FMI 3.0 implementer’s guide jointly published by prostep ivip and Modelica Association Project FMI
```suggestion
#### FMI 3.0 Implementers' Guide jointly published by prostep ivip and Modelica Association Project FMI
```

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +It has been developed jointly by prostep ivip and the Modelica Association Project FMI.
```suggestion
It has been developed jointly by the prostep ivip Smart Systems Engineering project and the Modelica Association Project FMI.
```

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +The FMI 3.0 implementer’s guide provides best practice recommendations to implementers of FMI, focusing on FMI 3.0, derived from the industrial experience of the prostep Smart Systems Engineering pro
```suggestion
The FMI 3.0 Implementers' Guide provides best practice recommendations to implementers of FMI, focusing on FMI 3.0, derived from the industrial experience of the prostep Smart Systems Engineering project members and the FMI community in employing FMI.
```

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +All of the content is to be considered non-normative and shall not be considered to supplant any normative statement in the FMI 3.0 standard.
```suggestion
The overarching goal of the recommendations is to aid interoperability of FMI implementations and ensure good ease-of-use for end users in employing FMI. 
The FMI 3.0 Implementers' Guide is intended for tool vendors planning to support FMI in their products, for importing and exporting FMUs.
It assumes a technical audience familiar with the specification documents and tries to give further information and hints in areas where either the relevant specification documents have been found less clear than expected or where user expectations are relevant to implementation choices.
It also considers errors and bugs encountered in the practical use of existing FMI implementations and guides to avoid common pitfalls.
It is intended as a living document and will be maintained and expanded over time as new issues or needs for clarification appear.
All of the content is to be considered non-normative and shall not be considered to supplant any normative statement in the FMI 3.0 standard.
```

2023-03-04 12:36 UTC, pmai commented on _2023-01/fmi3-ig-published.md
> +The prostep ivip Association is an international association committed to the development of innovative approaches to solving problems and modern standards for product data management and virtual pro
```suggestion
The prostep ivip association is an international association committed to the development of innovative approaches to solving problems and modern standards for product data management and virtual product creation.
It bundles the interests of manufacturers and suppliers in manufacturing industry as well as IT vendors, in close cooperation with research and science institutes, to provide its members with the long-term competitive advantages that more efficient processes, methods and systems provide.
The prostep ivip Smart Systems Engineering project develops recommendations for process design, promotes technical standards for the cooperative development of complex mechatronic systems, and supports the creation of transparency with regard to systems engineering objects both within and across companies.
```

2023-03-05 20:10 UTC, merged