American Modelica Conference Announcement
modelica/newsletter pull request #287
Opened 2024-02-27 18:08 UTC by lvanfretti

Initial announcement for review.

2024-02-27 19:27 UTC, mwetter commented on _2024-01/AmericanModelicaConference.md
> +The conference will take place at the **University of Connecticut in Storrs** in the [Innovation Partnership Building](https://techpark.uconn.edu/) from **October 14–16, 2024**. It is organized by [N
Change North American Modelica Users Group to
North American Modelica Users' Group

2024-02-27 19:28 UTC, mwetter commented on _2024-01/AmericanModelicaConference.md
> +In addition to paper presentations, the conference features several Modelica tutorials for beginners and advanced users, as well as industrial user presentations, vendor sessions, and an exhibition.
Replace "Europe" by "other continents"

2024-02-27 19:30 UTC, mwetter requested changes
@lvanfretti : Please see inline comments (as I don't have write access).

2024-02-27 19:46 UTC, lvanfretti commented on _2024-01/AmericanModelicaConference.md
> +The conference will take place at the **University of Connecticut in Storrs** in the [Innovation Partnership Building](https://techpark.uconn.edu/) from **October 14–16, 2024**. It is organized by [N
Applied in [7455e35](https://github.com/modelica/newsletter/pull/287/commits/7455e357f459e9eead09c07e556b81bc00a0b46d)

2024-02-27 19:46 UTC, lvanfretti commented on _2024-01/AmericanModelicaConference.md
> +In addition to paper presentations, the conference features several Modelica tutorials for beginners and advanced users, as well as industrial user presentations, vendor sessions, and an exhibition.
Applied in [7455e35](https://github.com/modelica/newsletter/pull/287/commits/7455e357f459e9eead09c07e556b81bc00a0b46d)

2024-02-27 19:46 UTC, lvanfretti commented
> @lvanfretti : Please see inline comments (as I don't have write access).

2024-02-27 19:47 UTC, lvanfretti commented
@mwetter I've applied your suggestions [7455e35](https://github.com/modelica/newsletter/pull/287/commits/7455e357f459e9eead09c07e556b81bc00a0b46d)

2024-02-27 20:44 UTC, mwetter approved these changes

2024-03-05 22:47 UTC, lvanfretti commented
@filip-jezek this is ready for your review.

2024-03-10 17:20 UTC, merged