FMI Rules Update clarifying membership
modelica/newsletter pull request #289
Opened 2024-03-05 20:36 UTC by chrbertsch

2024-03-06 12:38 UTC, t-sommer requested changes

2024-03-06 12:38 UTC, t-sommer commented on _2024-01/FMI-Rules-Membership.md
> +If your organization of company is interested in joining the FMI Project as a contributing member or become part of Advisory Committee, please write to contact@fmi-standard.org.
Shouldn't this be "organization _or_ company"?

2024-03-06 12:50 UTC, t-sommer approved these changes

2024-03-07 06:05 UTC, beutlich commented on _2024-01/FMI-Rules-Membership.md
> +The FMI Steering Committee has approved [new rules](/about/#project-rules) for the FMI Project that clarify the different rights and duties of project members.
```suggestion
The FMI Steering Committee has approved [new rules](https://fmi-standard.org/about/#project-rules) for the FMI Project that clarify the different rights and duties of project members. 
```

2024-03-10 17:22 UTC, merged